#! /bin/bash

echo "[INFO]: Obtaining the 'tb3_2022.sh' setup script from GitHub..."

cd ~/.tb3_tools/
wget https://raw.githubusercontent.com/tom-howard/tuos_robotics/main/turtlebot3/tb3_2022.sh

echo "[INFO]: Executing setup script..."

chmod +x tb3_2022.sh && ./tb3_2022.sh $1
