#!/bin/bash

if [[ ! $(sudo echo 0) ]]; then
    echo "Invalid credentials. Exiting."
    exit
fi

cd ~

rm -rf ~/tuos_robotics

if ! git clone https://github.com/tom-howard/tuos_robotics.git; then
    echo "Error."
else
    # /usr/local/bin
    cd /usr/local/bin
    files="ask_user.sh cleanup_env robot_switch rosbackup.sh rosrestore.sh update_wsl_ros_scripts wsl_ros"
    sudo rm -f $files
    cd ~/tuos_robotics/wsl/
    sudo cp $files /usr/local/bin/
    cd /usr/local/bin
    sudo chmod +x $files
    
    # ~/.wsl-ros/
    files="bashrc_wsl_ros bashrc_miro bashrc_turtlebot3 get_tuos_user.sh set_display.sh default_backup_exclusions"
    cd ~/.wsl-ros/
    rm -f $files
    cd ~/tuos_robotics/wsl/
    cp $files ~/.wsl-ros/
    
    # ~
    rm -f ~/.bash_aliases
    cd ~/tuos_robotics/wsl/
    cp .bash_aliases ~/
    
    rm -rf ~/tuos_robotics
    
    cd ~
    echo "Done."
fi
