#!/usr/bin/env bash
# locate in: /usr/local/bin/

IT='\033[3m'
NC='\033[0m'

ask() {
  # adapted from https://gist.github.com/davejamesmiller/1965569
  local prompt default reply
  prompt='y/n'
  default=''
  while true; do
    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "
    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read -r reply </dev/tty
    # Default?
    if [[ -z $reply ]]; then
      reply=$default
    fi
    # Check if the reply is valid
    case "$reply" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac
  done
}

if [ ! -f ~/.wsl-ros/backup_dir.sh ]; then
  # no backup_dir script exists so create a default:
  echo "export WSL_ROS_BACKUP_PATH=u" > ~/.wsl-ros/backup_dir.sh
fi
source ~/.wsl-ros/backup_dir.sh

COMMAND=$1
# INPUT CHECKS
if ([[ $# -eq 2 ]] && [[ "$COMMAND" == "backup" ]]) || ([[ $# -eq 2 ]] && [[ "$COMMAND" == "restore" ]]); then
  BACKUP_FILE_PATH_FULL=$2
  BACKUP_FILE_PATH_NOEX="${BACKUP_FILE_PATH_FULL%.*}"
  BACKUP_FILE_NAME=$(basename $BACKUP_FILE_PATH_FULL .tar.gz)
  BACKUP_ROOT_DIR=${BACKUP_FILE_PATH_FULL%/*}    
else
  BACKUP_FILE_NAME=ros-backup-$(echo $WSL_ROS_VER | sed "s/[^0-9']//g")
  BACKUP_ROOT_DIR=/mnt/"$WSL_ROS_BACKUP_PATH"
  BACKUP_FILE_PATH_NOEX="$BACKUP_ROOT_DIR"/wsl-ros/"$BACKUP_FILE_NAME"
  BACKUP_FILE_PATH_FULL=$BACKUP_FILE_PATH_NOEX'.tar.gz'
fi

BACKUP_FILE_DIR=${BACKUP_FILE_PATH_FULL%/*}
BACKUP_FILE_PATH_WINDOWS=$(sed "s/\/mnt\/u/U\:/;s/\//\\\/g" <<< "$BACKUP_FILE_PATH_FULL")
BACKUP_LOGFILE=$BACKUP_FILE_PATH_NOEX'-log.txt'

if [ ! -d "$BACKUP_ROOT_DIR" ]; then
  echo "Error: can't access $BACKUP_ROOT_DIR"
  exit 1
fi

usage() {
  echo -e "${IT}wsl_ros${NC} backup/restore/update tool.

  Usage:
  $ wsl_ros [COMMAND]

  [COMMAND] options:
    backup    ${IT}Backup${NC} files in your WSL home directory.
    restore   ${IT}Restore${NC} an existing backup file.
    update    ${IT}Update${NC} all custom TUoS WSL-ROS scripts (if applicable).

  Backup file: "
  echo "    $BACKUP_FILE_PATH_WINDOWS"
}

backup_exists() {
  if [ -f $BACKUP_FILE_PATH_FULL ]; then
    return 0
  else
    return 1
  fi
}

touch_backup() {
  if ! touch $BACKUP_LOGFILE; then
    echo "Error: unable to access a backup file at:"
    echo "  $BACKUP_FILE_PATH_WINDOWS"
    exit 1
  fi
}

archive_backup() {
  archive_dir=$BACKUP_FILE_DIR/archive
  mkdir -p $archive_dir
  cp $BACKUP_FILE_PATH_FULL $BACKUP_FILE_DIR/archive/$BACKUP_FILE_NAME"-$(date "+%Y%m%d%H%M%S").tar.gz"
  check_dir=true
  while [ "$check_dir" = true ]; do
    archive_num=$(find $archive_dir -type f | wc -l)
    if [ $archive_num -gt 5 ]; then
      # check for oldest file according to last modified:
      oldest=$(find $archive_dir -type f -printf '%p\n' | sort | head -n 1)
      # remove oldest:
      rm $oldest
    else
      check_dir=false
    fi
  done
}

backup() {
  if [ ! -f ~/.backup_exclusions ]; then
    # no exclusions file exists in ~, so load a default:
    cp ~/.wsl-ros/default_backup_exclusions ~/.backup_exclusions
  fi

  echo "Backing up your WSL-ROS environment to '$BACKUP_FILE_PATH_WINDOWS', please wait..."

  mkdir -p $BACKUP_FILE_DIR

  touch_backup

  if tar -X $HOME/.backup_exclusions --exclude='.wsl-ros' --checkpoint=.200 -cjf $BACKUP_FILE_PATH_FULL -C $HOME .; then
    echo "$(date): Backup from $(hostname) [wsl-ros version: $WSL_ROS_VER]" >> $BACKUP_LOGFILE
    echo -e ".\nBackup complete."
  else
    echo -e "An error occurred during the backup process...\nYOUR DATA MAY NOT HAVE BEEN BACKED UP CORRECTLY."
  fi
}

restore() {
  echo "Restoring your files from '$BACKUP_FILE_PATH_WINDOWS', please wait..."
  
  touch_backup

  if tar --checkpoint=.200 -xjf $BACKUP_FILE_PATH_FULL -C $HOME ; then
    echo "$(date): Restore to $(hostname) [wsl-ros version: $WSL_ROS_VER]" >> $BACKUP_LOGFILE
    echo -e ".\nRestore complete."
  else
    echo -e "An error occurred during the restore process...\nYOUR DATA MAY NOT HAVE BEEN RECOVERED CORRECTLY."
  fi
}

check_for_updates() {
  wget -qO ~/.wsl-ros/remote_ver https://raw.githubusercontent.com/tom-howard/tuos_robotics/main/wsl/remote_ver 

  LOCAL_VER=$(cat ~/.wsl-ros/local_ver)
  REMOTE_VER=$(cat ~/.wsl-ros/remote_ver)

  if [ $REMOTE_VER -gt $LOCAL_VER ]; then
    echo "Updating WSL-ROS scripts..."
    diamond_tools update
    echo "$REMOTE_VER" > ~/.wsl-ros/local_ver
  fi
}

if [[ "$COMMAND" == "" ]]; then
  echo -e "No input command provided...\n"
  usage
  exit 1
fi

case $COMMAND in
  backup)
    if backup_exists; then
      echo -e "Preparing to backup your WSL-ROS environment to:"
      echo "  $BACKUP_FILE_PATH_WINDOWS"
      echo "***This will overwrite your existing WSL-ROS backup!***" 
      if ask "Are you sure you want to continue?"; then
        archive_backup
        backup
      else
        echo "Backup cancelled."
        exit 1
      fi
    else
      backup
    fi
    ;;
  restore)
    if backup_exists; then
      echo -e "Preparing to restore from a previous WSL-ROS backup:"
      echo "  $BACKUP_FILE_PATH_WINDOWS"
      if ask "Do you want to continue?"; then
        restore
      else
        echo "Restore cancelled."
        exit 1
      fi
    else
      echo "Unable to restore! The file '$BACKUP_FILE_PATH_WINDOWS' does not exist."
      exit 1
    fi
    ;;
  first-launch)
    echo "Welcome to WSL-ROS!"
    check_for_updates
    if backup_exists; then
      echo -e "It looks like you already have a backup from a previous session:"
      echo "  $BACKUP_FILE_PATH_WINDOWS"
      if ask "Do you want to restore this now?"; then
        restore
      else
        echo "Nothing was restored. Starting from fresh."
        exit 1
      fi
    fi
    ;;
  update)
    check_for_updates
    ;;  
  *)
    echo -e "'$COMMAND' is not a vaild input, see below for options...\n"
    usage
    exit 1
    ;;
esac

