#!/usr/bin/env bash

# CC BY-NC
# Tom Howard, University of Sheffield
# Copyright (c) 2024

# Text formatting:
RED='\033[0;31m'
GRN='\033[0;32m'
YEL='\033[0;93m'
BLU='\033[1;34m'
CYN='\033[0;96m'
EM='\033[3m' # italic
NDF='\033[0m'

USAGE="${EM}waffle${NDF} command line interface for The University of Sheffield TurtleBot3
Waffles.

Usage: waffle [VERB] [ARGS]

[VERB] options:
  pair    ${EM}Pair${NDF} this laptop to the specified robot (dia-waffle[NUM]):
          
          Usage: waffle pair [NUM] [OPTIONS]
          
          [NUM]   (Required) Numeric ID of the robot you are working with 
                  (a number between 1 and 50) e.g. ${EM}dia-waffle[NUM]${NDF}.

          Additional [OPTION]s:
            quick | q
                  Quick pair - do not synchronise system clocks.

  sync    Manually ${EM}sync${NDF}hronise both system clocks to a common NTP Server.
  term    Launch a (tmux) ${EM}term${NDF}inal instance on the paired robot
          (dia-waffle[NUM]).
  bridge  Launch a Zenoh ${EM}bridge${NDF} to connect the laptop with the paired
          robot (dia-waffle[NUM])
  ping    Look for the paired robot (dia-waffle[NUM]) on the network by
          ${EM}ping${NDF}ing it.
  off     Shutdown the robot.
"

# Internal functions

ask() {
  local reply prompt
  prompt='y/n'
  echo -e -n "${YEL}[INPUT]${NDF} $1 [$prompt] >> "
  read -r reply </dev/tty
  if [[ -z $reply ]]; then
    return 1;
  elif [ "$reply" == "y" ] || [ "$reply" == "Y" ]; then
    return 0;
  else
    return 1;
  fi
}

check-waffle-num-valid() {
  if [[ "$WAFFLE_NO" == "" ]]; then
    echo -e "${RED}No Waffle number provided${NDF}."
    echo -e $USAGE 
    exit 5
  elif (( $WAFFLE_NO < 1 || $WAFFLE_NO > 50 )); then
    echo -e "${RED}Not a valid Waffle number${NDF} ([NUM] must be between 1 and 50)"
    exit 5
  fi
}

get-waffle-id() {
  IDFILE=$HOME/.tuos/waffle_number
  if [[ ! -f "$IDFILE" ]];
    echo -e "This laptop (${CYN}dia-laptop$LAPTOP_NO${NDF}) is not currently paired with a robot."
    exit 5
  fi
  VALIDITYPERIOD=$((2*24*60*60)) # 2 days, in seconds
  TIMENOW=$(date +%s) # seconds
  FILELASTMOD=$(stat $IDFILE -c %Y) # seconds
  TIMESINCELASTMOD=$(expr $TIMENOW - $FILELASTMOD)

  if (( $TIMESINCELASTMOD > $VALIDITYPERIOD )); then
    echo -e "${RED}Pairing has expired${NDF}. To re-pair, run:"
    echo "  waffle pair [NUM]"
    exit 5
  else
    WAFFLE_NO=$(cat $IDFILE)
    check-waffle-num-valid
    echo -e "This laptop (${CYN}dia-laptop$LAPTOP_NO${NDF}) is currently paired with ${GRN}dia-waffle$WAFFLE_NO${NDF}."
  fi
}

# CLI entry points:

pair() {
  echo -e "You are about to pair ${CYN}dia-laptop$LAPTOP_NO${NDF} with ${GRN}dia-waffle$WAFFLE_NO${NDF}."
  if ask "OK to continue?"; then
    echo -e "${CYN}[$LAPTOP_ID]${NDF} Pairing in progress (this will take a minute)..."
    echo "$WAFFLE_NO" > $HOME/.tuos/waffle_number # set the waffle number

    WAFFLE_SSH_KEY=$HOME/.ssh/rsa_waffle$WAFFLE_NO
    # configuring ssh connection:
    mkdir -p $HOME/.ssh/
    rm -f $HOME/.ssh/rsa_waffle*
    ssh-keygen -t rsa -b 2048 -f $WAFFLE_SSH_KEY -q -N ""
    SSH_OPTS='-o IdentitiesOnly=yes' ssh-copy-id -i $WAFFLE_SSH_KEY robot@dia-waffle$WAFFLE_NO > /dev/null 2>&1
    ssh -o IdentitiesOnly=yes -i $WAFFLE_SSH_KEY robot@dia-waffle$WAFFLE_NO 'bash -s' < /usr/local/bin/robot_pairing.sh $LAPTOP_NO

    if [[ "$OPTION" != "quick" && "$OPTION" != "q" ]]; then
      sync
    fi
    check-pairing loud

    echo -e "${BLU}Pairing complete${NDF}."
  else
    echo -e "${RED}Pairing cancelled${NDF}."
  fi
}

ping-waffle() {
  # TODO: get waffle number!
  echo -e "${CYN}[$LAPTOP_ID]${NDF} Pinging ${GRN}dia-waffle$WAFFLE_NO${NDF}..."
  ping dia-waffle$WAFFLE_NO
}

# Main:

LAPTOP_ID=$(hostname)
LAPTOP_NO=$(hostname | grep -o -E '[0-9]+')

if [[ $# -lt 1 ]]; then
  echo -e $USAGE
  exit 5
fi

COMMAND=$1

case $COMMAND in
  pair)
    WAFFLE_NO=$2
    OPTION=$3
    echo "$COMMAND, $WAFFLE_NO, $OPTION"
    check-waffle-num-valid
    pair
    ;;
  sync|term|bridge|off)
    get-waffle-id
    echo "$COMMAND"
    ;;
  ping)
    ping-waffle
    ;;
  *)
    echo -e "${RED}[INVALID INPUT]...${NDF}"
    echo -e "$USAGE"
    exit 5
    ;;
esac
