#!/bin/bash
# /usr/local/bin/robot_switch

ERR_MSG="Not a valid input, use 'miro' or 'tb3'."

if [ $1 == '' ]; then
  echo "$ERR_MSG"
elif [ $1 == 'miro' ]; then
  printf "\e[38;5;169mMiRo mode. \e[38;5;015m (Run 'robot_switch tb3' to change mode)\n"
  echo "miro" > ~/.tuos/current_robot
  exec bash
elif [ $1 == 'tb3' ]; then
  printf "\e[38;5;9mTurtleBot3 Waffle mode. \e[38;5;015m (Run 'robot_switch miro' to change mode)\n"
  echo "turtlebot" > ~/.tuos/current_robot
  exec bash
else
  echo "$ERR_MSG"
fi
