#! /bin/bash
# ~/bin/copy_tuos_bash

sudo rm -r /home/student/.diamond/
sudo cp -r ~/.diamond/ /home/student/
sudo chown -hR student:student /home/student/.diamond
cd /home/student/.diamond/
sudo rm current_robot miro_number robot_mode waffle_number

ls -lF

cd ~
