#!/usr/bin/env bash

# Diamond Tools for TB3 Waffles

sudo_check() {
  if [[ ! $(sudo echo 0) ]]; then
    echo "Failed sudo check. Exiting."
    exit
  fi
}

SRC_DIR="/home/ros/repos/tuos_robotics"

update_src() {
  echo "Checking for updates..."
  cd $SRC_DIR && git pull --quiet
}

getx() {
  update_src

  SCRIPT=$1
  OPTS=$2
  COPY_SCRIPT="$SCRIPT-$(date +'%Y%m%d%H%M%S')"
  echo "[INFO]: Obtaining '$SCRIPT.sh' script..."

  cd $HOME/.tuos/diamond_tools/
  cp $SRC_DIR/turtlebot3/diamond_tools/$SCRIPT.sh ./$COPY_SCRIPT.sh

  wget -qO $COPY_SCRIPT.sh https://raw.githubusercontent.com/tom-howard/tuos_robotics/jazzy/turtlebot3/diamond_tools/$SCRIPT.sh
  echo "[INFO]: Executing..."
  chmod +x $COPY_SCRIPT.sh && ./$COPY_SCRIPT.sh $OPTS
}

if [[ $# -eq 0 ]]; then
  echo "No input command provided. Exiting."
  exit 1
else
  COMMAND=$1
  OPTION=$2
fi

case $COMMAND in 
  setup|s)
    sudo_check
    SCRIPT=tb3_setup
    getx $SCRIPT
    ;;
  update|u)
    sudo_check
    getx update_tools
    ;;
  workspace|w)
    sudo_check
    getx ros_ws $OPTION
    ;;
  *)
    echo "Not a valid input (use 'setup', 'update' or 'workspace')."
    exit 1
    ;;
esac
