#!/usr/bin/env bash

# Diamond Tools for TB3 Waffles
# locate in /usr/local/bin/

if [[ $# -eq 0 ]]; then
  echo "No input command provided. Exiting."
  exit 1
else
  COMMAND=$1
fi

sudo_check() {
  if [[ ! $(sudo echo 0) ]]; then
    echo "Failed sudo check. Exiting."
    exit
  fi
}

getx() {
  SCRIPT=$1
  echo "[INFO]: Obtaining '$SCRIPT' script from GitHub..."
  cd ~/.tb3_tools/
  rm -f $SCRIPT
  wget https://raw.githubusercontent.com/tom-howard/tuos_robotics/humble/turtlebot3/diamond_tools/$SCRIPT
  echo "[INFO]: Executing script..."
  chmod +x $SCRIPT && ./$SCRIPT
}

case $COMMAND in 
  setup)
    sudo_check
    if [[ $# -eq 1 ]]; then
      SCRIPT=tb3_setup.sh
    else
      SCRIPT=$2
    fi
    getx $SCRIPT
    ;;
  update)
    sudo_check
    getx update_tools.sh
    ;;
  catkin)
    sudo_check
    getx catkin_refresh.sh
    ;;
  *)
    echo "Not a valid input."
    exit 1
    ;;
esac
