# utility
alias src="echo 'Sourcing ~/.bashrc...' && source ~/.bashrc"
alias roscd="cd ~/ros2_ws/src"

# some useful TurtleBot3 commands:
alias tb3_teleop="ros2 run turtlebot3_teleop teleop_keyboard"
alias tb3_slam="ros2 launch tuos_tb3_tools slam.launch.py environment:=real"
alias tb3_nav="ros2 launch turtlebot3_navigation2 navigation2.launch.py"
alias tb3_map="ros2 launch nav2_map_server map_saver_server.launch.py"
alias tb3_rviz="ros2 launch tuos_tb3_tools rviz.launch.py"

# Sims
alias tb3_world="ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py"
alias tb3_sim="ros2 launch turtlebot3_gazebo empty_world.launch.py"

alias rtl="ros2 topic list"
alias rnl="ros2 node list"
alias rmwz="ros2 run rmw_zenoh_cpp rmw_zenohd"
alias clr_colcon_envs="unset COLCON_PREFIX_PATH AMENT_PREFIX_PATH CMAKE_PREFIX_PATH"
