#!/usr/bin/env bash

SCRIPT_NAME=$1

echo "[INFO]: Obtaining the '$SCRIPT_NAME' setup script from GitHub..."

cd ~/.tuos/
wget -O setup_script.sh https://raw.githubusercontent.com/tom-howard/tuos_robotics/main/laptops/$SCRIPT_NAME

echo "[INFO]: Executing setup script..."

chmod +x setup_script.sh && ./setup_script.sh

rm -rf ~/.tb3_tools/setup_script.sh