#!/bin/bash
# /usr/local/bin/pair_with_waffle

WAFFLE_NO=$1
ERR_MSG="Not a valid input. Please enter the number of the Waffle that you want to connect to (between 1 and 50)."

if [ "$WAFFLE_NO" == "" ]; then
    echo "$ERR_MSG"
elif (( $WAFFLE_NO >= 1 && $WAFFLE_NO <= 50 )); then
    echo "Pairing with robot: dia-waffle$1..."
    echo "$1" > ~/.tuos/waffle_number
    echo "Done. Re-source the .bashrc (by typing 'src') for the changes to take effect."
else
    echo "$ERR_MSG"
fi
