#!/bin/bash
# /usr/local/bin/pair_with_miro

MIRO_NO=$1
ERR_MSG="Not a valid input. Please enter the number of the MiRo that you want to connect to (between 1 and 40)."

if [ "$MIRO_NO" == "" ]; then
    echo "$ERR_MSG"
elif (( $MIRO_NO >= 1 && $MIRO_NO <= 40 )); then
    echo "Pairing with robot: dia-miro$1..."
    echo "$1" > ~/.tuos/miro_number
    echo "Done. Re-source the .bashrc (by typing 'src') for the changes to take effect."
else
    echo "$ERR_MSG"
fi
