#!/bin/bash

COMMANDS='sim | robot | ?'
USAGE="
A tool to switch between Simulation or Real Robot Hardware.

Usage:
   $(basename ${0}) { ${COMMANDS} }"

STATUS_FILE=${HOME}/.diamond/ros_mode

if [[ $# -eq 0 ]]; then
  echo "${USAGE}"
  exit 1
else
  COMMAND=$1
fi

if [[ "${COMMAND}" == "?"  ]]; then
  echo "Current mode is: '$(cat ${STATUS_FILE} 2>/dev/null)'"
  exit 1
elif [[ "${COMMAND}" == "sim" ]]; then
  echo "Switching into 'Simulation Mode' (run 'ros_mode robot' to work with a real robot)."
  echo "${COMMAND}" > ${STATUS_FILE}
elif [[ "${COMMAND}" == "robot" ]]; then
  echo "Switching into 'Real Robot Mode' (run 'ros_mode sim' to work in simulation instead)."
  echo "${COMMAND}" > ${STATUS_FILE}
else
  echo "Not a valid input."
  echo "${USAGE}"
  exit 1
fi

echo "Re-source your shell to apply changes."
