#!/usr/bin/env bash

# Diamond Tools for Robot Laptops:
# locate in /usr/local/bin/

sudo_check() {
  if [[ ! $(sudo echo 0) ]]; then
    echo "Did not pass sudo check. Exiting."
    exit
  fi
}

getx() {
  SCRIPT=$1
  LOCAL_SCRIPT="$SCRIPT-$(date +'%Y%m%d%H%M%S')"
  echo "[INFO]: Obtaining '$SCRIPT.sh' script from GitHub..."
  cd $HOME/.tuos/diamond_tools/
  wget -O $LOCAL_SCRIPT.sh https://raw.githubusercontent.com/tom-howard/tuos_robotics/humble/laptops/diamond_tools/$SCRIPT.sh
  echo "[INFO]: Executing script..."
  chmod +x $LOCAL_SCRIPT.sh && ./$LOCAL_SCRIPT.sh
}

if [[ $# -eq 0 ]]; then
  echo "No input command provided. Exiting."
  exit 1
else
  COMMAND=$1
fi

if [[ $(iwgetid -r) != "eduroam" ]]; then
  echo "Connecting to eduroam..."
  nmcli c up eduroam
fi

case $COMMAND in 
  setup)
    sudo_check
    if [[ $# -eq 1 ]]; then
      SCRIPT=laptop_setup
    else
      SCRIPT=$2
    fi
    getx $SCRIPT
    ;;
  update)
    sudo_check
    getx update_tools
    ;;
  workspace)
    getx ros_ws
    ;;
  *)
    echo "Not a valid input."
    exit 1
    ;;
esac
