#!/usr/bin/env bash

RED='\033[0;31m'
IT='\033[3m'
NC='\033[0m'

echo -e "${RED}Not available in WSL-ROS!${NC} \n    The ${IT}waffle Command Line Tool${NC} is only available on the Diamond's Robotics Laptops!"
